long_names = {
    'cdd': 'Consecutive Dry Days (PR<1mm)',
    'cwd': 'Consecutive Wet Days (PR>1mm)',
    'prcptot': 'Annual total wet-day PR (Sum PR>1mm)',
    'r10mm': 'Number of heavy rain days',
    'r20mm': 'Number of very heavy rain days',
    'r95p': 'Total annual PR from heavy rain days',
    'r99p': 'Total annual PR from very heavy rain days',
    'rx1day': 'Max 1-day PR',
    'rx5day': 'Max 5-day PR',
    'sdii': 'Daily PR intensity (Mean PR>1mm)',
    'csdi': 'Cold spell duration indicator (TN<daily 10p)',
    'fd': 'Frost Days (TN<0C)',
    'id': 'Ice Days (TX>0C)',
    'tn10p': 'Amount of cold nights (TN<daily 10p)',
    'tn90p': 'Amount of warm nights (TN>daily 90p)',
    'tnn': 'Min TN',
    'tnx': 'Max TN',
    'tr': 'Tropical nights (TN>20C)',
    'su': 'Summer days (TX>25C)',
    'tx10p': 'Amount of cool days (TX<daily 10p)',
    'tx90p': 'Amount of hot days (TX>daily 10p)',
    'txn': 'Min TX',
    'txx': 'Max TX',
    'wsdi': 'Warm spell duration indicator (TX>daily 90p)',
    'dtr': 'Daily Temperature Range (daily TX-TN)',
    'gsl': 'Growing Season Length',

    '10p': '10th percentile of daily TN',
    '90p': '90th percentile of daily TX',
}